#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh

init_tests \
	lddtree_usage \
	lddtree_version \
	lddtree_sh \
	lddtree_sh_list

lddtree_usage_body() {
	atf_check -o match:"Usage:" lddtree.sh -h
	atf_check -o match:"Usage:" lddtree.sh --help
	atf_check -s exit:1 -e match:"Usage:" lddtree.sh
}

lddtree_version_body() {
	for arg in -V --version; do
		atf_check -s exit:0 \
			-o match:'lddtree-[0-9]*.[0-9]*' \
			lddtree.sh "$arg"
	done
}

# test without -R
lddtree_sh_body() {
	atf_check -s exit:0 \
		-o match:'sh => /bin/sh \(interpreter .*\)' \
		lddtree.sh /bin/sh
}

# test without -R, flat output
# should only output lines prefixed with /
lddtree_sh_list_body() {
	for arg in -l --list; do
		atf_check -s exit:0 \
			-o match:'/bin/sh' \
			-o not-match:'\(interpreter .*\)' \
			-o not-match:'^[^/]' \
			lddtree.sh "$arg" /bin/sh
	done
}
